import { defineComponent, provide } from 'vue';

import CountryService from './country/country.service';
import ProvinceService from './province/province.service';
import TownCityService from './town-city/town-city.service';
import DistrictService from './district/district.service';
import CommonLocalityService from './common-locality/common-locality.service';
import TenantService from './tenant/tenant.service';
import TypeOfOrganizationService from './type-of-organization/type-of-organization.service';
import OrganizationService from './organization/organization.service';
import BusinessUnitService from './business-unit/business-unit.service';
import OrganizationDomainService from './organization-domain/organization-domain.service';
import OrganizationAttributeService from './organization-attribute/organization-attribute.service';
import TypeOfPersonService from './type-of-person/type-of-person.service';
import PersonService from './person/person.service';
import OrganizationRoleService from './organization-role/organization-role.service';
import OrganizationMembershipService from './organization-membership/organization-membership.service';
import OrganizationMemberRoleService from './organization-member-role/organization-member-role.service';
import AssetTypeService from './asset-type/asset-type.service';
import RawAssetProcTmpService from './raw-asset-proc-tmp/raw-asset-proc-tmp.service';
import AssetService from './asset/asset.service';
import AssetMetadataService from './asset-metadata/asset-metadata.service';
import AssetCollectionService from './asset-collection/asset-collection.service';
import InvoiceService from './invoice/invoice.service';
import PaymentGatewayService from './payment-gateway/payment-gateway.service';
import PaymentService from './payment/payment.service';
import WarehouseService from './warehouse/warehouse.service';
import SupplierService from './supplier/supplier.service';
import BrandService from './brand/brand.service';
import ProductService from './product/product.service';
import InventoryTransactionService from './inventory-transaction/inventory-transaction.service';
import StockLevelService from './stock-level/stock-level.service';
import CustomerService from './customer/customer.service';
import CustomerTypeService from './customer-type/customer-type.service';
import CategoryService from './category/category.service';
import ArticleService from './article/article.service';
import OrderService from './order/order.service';
import OrderItemService from './order-item/order-item.service';
import TypeOfArtmediaService from './type-of-artmedia/type-of-artmedia.service';
import TypeOfArtistService from './type-of-artist/type-of-artist.service';
import ArtisticGenreService from './artistic-genre/artistic-genre.service';
import ArtistService from './artist/artist.service';
import ArtworkService from './artwork/artwork.service';
import ArtworkCastService from './artwork-cast/artwork-cast.service';
import TypeOfEventService from './type-of-event/type-of-event.service';
import TypeOfVenueService from './type-of-venue/type-of-venue.service';
import TypeOfActivityService from './type-of-activity/type-of-activity.service';
import VenueService from './venue/venue.service';
import ActivityService from './activity/activity.service';
import EventService from './event/event.service';
import ProgramService from './program/program.service';
import EventProgramService from './event-program/event-program.service';
import ScheduledActivityService from './scheduled-activity/scheduled-activity.service';
import EventAttendeeService from './event-attendee/event-attendee.service';
import TicketPurchasedService from './ticket-purchased/ticket-purchased.service';
// jhipster-needle-add-entity-service-to-entities-component-import - JHipster will import entities services here

export default defineComponent({
  compatConfig: { MODE: 3 },
  name: 'Entities',
  setup() {
    provide('countryService', () => new CountryService());
    provide('provinceService', () => new ProvinceService());
    provide('townCityService', () => new TownCityService());
    provide('districtService', () => new DistrictService());
    provide('commonLocalityService', () => new CommonLocalityService());
    provide('tenantService', () => new TenantService());
    provide('typeOfOrganizationService', () => new TypeOfOrganizationService());
    provide('organizationService', () => new OrganizationService());
    provide('businessUnitService', () => new BusinessUnitService());
    provide('organizationDomainService', () => new OrganizationDomainService());
    provide('organizationAttributeService', () => new OrganizationAttributeService());
    provide('typeOfPersonService', () => new TypeOfPersonService());
    provide('personService', () => new PersonService());
    provide('organizationRoleService', () => new OrganizationRoleService());
    provide('organizationMembershipService', () => new OrganizationMembershipService());
    provide('organizationMemberRoleService', () => new OrganizationMemberRoleService());
    provide('assetTypeService', () => new AssetTypeService());
    provide('rawAssetProcTmpService', () => new RawAssetProcTmpService());
    provide('assetService', () => new AssetService());
    provide('assetMetadataService', () => new AssetMetadataService());
    provide('assetCollectionService', () => new AssetCollectionService());
    provide('invoiceService', () => new InvoiceService());
    provide('paymentGatewayService', () => new PaymentGatewayService());
    provide('paymentService', () => new PaymentService());
    provide('warehouseService', () => new WarehouseService());
    provide('supplierService', () => new SupplierService());
    provide('brandService', () => new BrandService());
    provide('productService', () => new ProductService());
    provide('inventoryTransactionService', () => new InventoryTransactionService());
    provide('stockLevelService', () => new StockLevelService());
    provide('customerService', () => new CustomerService());
    provide('customerTypeService', () => new CustomerTypeService());
    provide('categoryService', () => new CategoryService());
    provide('articleService', () => new ArticleService());
    provide('orderService', () => new OrderService());
    provide('orderItemService', () => new OrderItemService());
    provide('typeOfArtmediaService', () => new TypeOfArtmediaService());
    provide('typeOfArtistService', () => new TypeOfArtistService());
    provide('artisticGenreService', () => new ArtisticGenreService());
    provide('artistService', () => new ArtistService());
    provide('artworkService', () => new ArtworkService());
    provide('artworkCastService', () => new ArtworkCastService());
    provide('typeOfEventService', () => new TypeOfEventService());
    provide('typeOfVenueService', () => new TypeOfVenueService());
    provide('typeOfActivityService', () => new TypeOfActivityService());
    provide('venueService', () => new VenueService());
    provide('activityService', () => new ActivityService());
    provide('eventService', () => new EventService());
    provide('programService', () => new ProgramService());
    provide('eventProgramService', () => new EventProgramService());
    provide('scheduledActivityService', () => new ScheduledActivityService());
    provide('eventAttendeeService', () => new EventAttendeeService());
    provide('ticketPurchasedService', () => new TicketPurchasedService());
    // jhipster-needle-add-entity-service-to-entities-component - JHipster will import entities services here
  },
});
