package org.dexterity.darueira.azimuteerp.monolith.springvue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeOfVenueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfVenueAllPropertiesEquals(TypeOfVenue expected, TypeOfVenue actual) {
        assertTypeOfVenueAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeOfVenueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfVenueAllUpdatablePropertiesEquals(TypeOfVenue expected, TypeOfVenue actual) {
        assertTypeOfVenueUpdatableFieldsEquals(expected, actual);
        assertTypeOfVenueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfVenueAutoGeneratedPropertiesEquals(TypeOfVenue expected, TypeOfVenue actual) {
        assertThat(expected)
            .as("Verify TypeOfVenue auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfVenueUpdatableFieldsEquals(TypeOfVenue expected, TypeOfVenue actual) {
        assertThat(expected)
            .as("Verify TypeOfVenue relevant properties")
            .satisfies(e -> assertThat(e.getAcronym()).as("check acronym").isEqualTo(actual.getAcronym()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getHandlerClazzName()).as("check handlerClazzName").isEqualTo(actual.getHandlerClazzName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfVenueUpdatableRelationshipsEquals(TypeOfVenue expected, TypeOfVenue actual) {}
}
