package org.dexterity.darueira.azimuteerp.monolith.springvue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeOfArtmediaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfArtmediaAllPropertiesEquals(TypeOfArtmedia expected, TypeOfArtmedia actual) {
        assertTypeOfArtmediaAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeOfArtmediaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfArtmediaAllUpdatablePropertiesEquals(TypeOfArtmedia expected, TypeOfArtmedia actual) {
        assertTypeOfArtmediaUpdatableFieldsEquals(expected, actual);
        assertTypeOfArtmediaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfArtmediaAutoGeneratedPropertiesEquals(TypeOfArtmedia expected, TypeOfArtmedia actual) {
        assertThat(expected)
            .as("Verify TypeOfArtmedia auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfArtmediaUpdatableFieldsEquals(TypeOfArtmedia expected, TypeOfArtmedia actual) {
        assertThat(expected)
            .as("Verify TypeOfArtmedia relevant properties")
            .satisfies(e -> assertThat(e.getAcronym()).as("check acronym").isEqualTo(actual.getAcronym()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfArtmediaUpdatableRelationshipsEquals(TypeOfArtmedia expected, TypeOfArtmedia actual) {}
}
