package org.dexterity.darueira.azimuteerp.monolith.springvue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeOfOrganizationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfOrganizationAllPropertiesEquals(TypeOfOrganization expected, TypeOfOrganization actual) {
        assertTypeOfOrganizationAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeOfOrganizationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfOrganizationAllUpdatablePropertiesEquals(TypeOfOrganization expected, TypeOfOrganization actual) {
        assertTypeOfOrganizationUpdatableFieldsEquals(expected, actual);
        assertTypeOfOrganizationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfOrganizationAutoGeneratedPropertiesEquals(TypeOfOrganization expected, TypeOfOrganization actual) {
        assertThat(expected)
            .as("Verify TypeOfOrganization auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfOrganizationUpdatableFieldsEquals(TypeOfOrganization expected, TypeOfOrganization actual) {
        assertThat(expected)
            .as("Verify TypeOfOrganization relevant properties")
            .satisfies(e -> assertThat(e.getAcronym()).as("check acronym").isEqualTo(actual.getAcronym()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(
                e -> assertThat(e.getBusinessHandlerClazz()).as("check businessHandlerClazz").isEqualTo(actual.getBusinessHandlerClazz())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfOrganizationUpdatableRelationshipsEquals(TypeOfOrganization expected, TypeOfOrganization actual) {}
}
