package org.dexterity.darueira.azimuteerp.monolith.springvue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeOfEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfEventAllPropertiesEquals(TypeOfEvent expected, TypeOfEvent actual) {
        assertTypeOfEventAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeOfEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfEventAllUpdatablePropertiesEquals(TypeOfEvent expected, TypeOfEvent actual) {
        assertTypeOfEventUpdatableFieldsEquals(expected, actual);
        assertTypeOfEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfEventAutoGeneratedPropertiesEquals(TypeOfEvent expected, TypeOfEvent actual) {
        assertThat(expected)
            .as("Verify TypeOfEvent auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfEventUpdatableFieldsEquals(TypeOfEvent expected, TypeOfEvent actual) {
        assertThat(expected)
            .as("Verify TypeOfEvent relevant properties")
            .satisfies(e -> assertThat(e.getAcronym()).as("check acronym").isEqualTo(actual.getAcronym()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getHandlerClazzName()).as("check handlerClazzName").isEqualTo(actual.getHandlerClazzName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfEventUpdatableRelationshipsEquals(TypeOfEvent expected, TypeOfEvent actual) {}
}
