package org.dexterity.darueira.azimuteerp.monolith.springvue.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeOfActivityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfActivityAllPropertiesEquals(TypeOfActivity expected, TypeOfActivity actual) {
        assertTypeOfActivityAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeOfActivityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfActivityAllUpdatablePropertiesEquals(TypeOfActivity expected, TypeOfActivity actual) {
        assertTypeOfActivityUpdatableFieldsEquals(expected, actual);
        assertTypeOfActivityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfActivityAutoGeneratedPropertiesEquals(TypeOfActivity expected, TypeOfActivity actual) {
        assertThat(expected)
            .as("Verify TypeOfActivity auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfActivityUpdatableFieldsEquals(TypeOfActivity expected, TypeOfActivity actual) {
        assertThat(expected)
            .as("Verify TypeOfActivity relevant properties")
            .satisfies(e -> assertThat(e.getAcronym()).as("check acronym").isEqualTo(actual.getAcronym()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getHandlerClazzName()).as("check handlerClazzName").isEqualTo(actual.getHandlerClazzName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeOfActivityUpdatableRelationshipsEquals(TypeOfActivity expected, TypeOfActivity actual) {}
}
