export enum CustomerStatusEnum {
  UNDER_EVALUATION = 'UNDER_EVALUATION',

  ONBOARDING = 'ONBOARDING',

  READY_TO_START = 'READY_TO_START',

  WORKING = 'WORKING',

  PENDENT = 'PENDENT',

  IN_FAILURE = 'IN_FAILURE',
}
