export enum PreferredPurposeEnum {
  USER_AVATAR = 'USER_AVATAR',

  LOGO_IMG = 'LOGO_IMG',

  PHOTO_ALBUM = 'PHOTO_ALBUM',

  ANY_OFFICE_FILE_TYPE = 'ANY_OFFICE_FILE_TYPE',

  EXECUTABLE_PROGRAM_BINARY = 'EXECUTABLE_PROGRAM_BINARY',

  OTHER = 'OTHER',
}
