export enum StatusRawProcessingEnum {
  UPLOADING = 'UPLOADING',

  UPLOADED = 'UPLOADED',

  WAITING_FOR_PROCESSING = 'WAITING_FOR_PROCESSING',

  PROCESSING = 'PROCESSING',

  DONE = 'DONE',

  FAILURE = 'FAILURE',
}
