export enum StorageTypeEnum {
  BLOB_IN_DB = 'BLOB_IN_DB',

  LOCAL_FILESYSTEM = 'LOCAL_FILESYSTEM',

  LOCAL_MINIO = 'LOCAL_MINIO',

  REMOTE_FILESYSTEM = 'REMOTE_FILESYSTEM',

  REMOTE_MINIO = 'REMOTE_MINIO',

  AWS_S3 = 'AWS_S3',

  OTHER_CLOUD_STORAGE = 'OTHER_CLOUD_STORAGE',
}
